version: "3.1" 

services:

  exim4:
    image: imixs/exim4
    container_name: "smarthost"
    restart: always
    ports:
      - "25:25"
    environment:
      EXIM_SMARTHOST: "smtp.strato.de:465"
      EXIM_PASSWORD: "smtp.strato.de:${STRATO_USER}:${STRATO_PASSWORT}"
    networks:
      - exim
networks:
  exim:
    name: "exim"
    external: true
